var cogMeta = {
  state: {
    'name': 'state',
    'type': 'cat',
    'desc': 'conditioning variable',
    'group': 'condVar',
    'defLabel': true,
    'defActive': true,
    'filterable': true,
    'filter': null,
    'sort': null,
    'plotData': [
      {'id': 'DC','ct': 1},
      {'id': 'DE','ct': 3},
      {'id': 'RI','ct': 5},
      {'id': 'CT','ct': 8},
      {'id': 'NH','ct': 10},
      {'id': 'MA','ct': 14},
      {'id': 'VT','ct': 14},
      {'id': 'AZ','ct': 15},
      {'id': 'NV','ct': 15},
      {'id': 'ME','ct': 16},
      {'id': 'NJ','ct': 21},
      {'id': 'ND','ct': 23},
      {'id': 'WY','ct': 23},
      {'id': 'MD','ct': 24},
      {'id': 'UT','ct': 27},
      {'id': 'NM','ct': 30},
      {'id': 'SD','ct': 35},
      {'id': 'OR','ct': 36},
      {'id': 'WA','ct': 39},
      {'id': 'MT','ct': 42},
      {'id': 'ID','ct': 43},
      {'id': 'SC','ct': 46},
      {'id': 'NE','ct': 50},
      {'id': 'WV','ct': 55},
      {'id': 'CA','ct': 58},
      {'id': 'LA','ct': 60},
      {'id': 'CO','ct': 61},
      {'id': 'NY','ct': 62},
      {'id': 'AL','ct': 64},
      {'id': 'FL','ct': 67},
      {'id': 'PA','ct': 67},
      {'id': 'AR','ct': 71},
      {'id': 'OK','ct': 72},
      {'id': 'WI','ct': 72},
      {'id': 'MS','ct': 73},
      {'id': 'KS','ct': 75},
      {'id': 'MI','ct': 83},
      {'id': 'MN','ct': 83},
      {'id': 'OH','ct': 88},
      {'id': 'IN','ct': 92},
      {'id': 'TN','ct': 95},
      {'id': 'IA','ct': 96},
      {'id': 'IL','ct': 99},
      {'id': 'NC','ct': 100},
      {'id': 'KY','ct': 111},
      {'id': 'MO','ct': 112},
      {'id': 'VA','ct': 133},
      {'id': 'GA','ct': 157},
      {'id': 'TX','ct': 208}
    ]
  },
  test: {
    'name': 'test',
    'type': 'cat',
    'desc': 'test cognostic',
    'group': 'common',
    'defLabel': false,
    'defActive': true,
    'filterable': true,
    'filter': null,
    'sort': null,
    'plotData': [
      {'id': 'Apples', 'ct': 28},
      {'id': 'Bananas', 'ct': 55},
      {'id': 'Carrots', 'ct': 43},
      {'id': 'Didgeridoos', 'ct': 91},
      {'id': 'Elephants', 'ct': 81},
      {'id': 'Falcons', 'ct': 53},
      {'id': 'Goats', 'ct': 19},
      {'id': 'Horses', 'ct': 87}
    ]
  },
  slope: {
    'name': 'slope',
    'type': 'num',
    'desc': 'list price slope',
    'group': 'common',
    'defLabel': false,
    'defActive': true,
    'filterable': true,
    'filter': null,
    'sort': null,
    'plotData': [
      {'x': -0.4,'y': 1},
      {'x': -0.35,'y': 0},
      {'x': -0.3,'y': 0},
      {'x': -0.25,'y': 0},
      {'x': -0.2,'y': 0},
      {'x': -0.15,'y': 2},
      {'x': -0.1,'y': 18},
      {'x': -0.05,'y': 1699},
      {'x': 0,'y': 1115},
      {'x': 0.05,'y': 15},
      {'x': 0.1,'y': 1},
      {'x': 0.15,'y': 1},
      {'x': 0.2,'y': 1},
      {'x': 0.25,'y': 0}
    ]
  }
}

export default cogMeta
