var appConstants = {
  ACTIVE_SIDEBAR: "ACTIVE_SIDEBAR",
  F_SELECT_NONE: "F_SELECT_NONE",
  F_SELECT: "F_SELECT",
  F_REGEX: "F_REGEX",
  F_ORDER: "F_ORDER",
  F_START_INDEX: "F_START_INDEX",
  F_TOGGLE_ACTIVE: "F_TOGGLE_ACTIVE",
  F_RESET: "F_RESET",
  F_UPDATE_HEIGHT: "F_UPDATE_HEIGHT"
}

module.exports = appConstants
